---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: readyimage-controller
  namespace: default
automountServiceAccountToken: true

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: control-readyimage
  namespace: default
rules:
  - apiGroups: ["qualified.io"]
    resources: ["readyimages", "readyimages/status"]
    verbs:
      - create
      - get
      - patch
      - delete
      - list
      - watch
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - deletecollection

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: readyimage-controller-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    namespace: default
    name: readyimage-controller
roleRef:
  kind: Role
  name: control-readyimage
  apiGroup: rbac.authorization.k8s.io
